version: 2.1

jobs:
  build: #building environment
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test: #testing 
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deploy: #deploying 
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: echo "Deploying to production server"

workflows: #creating worlkflows to execute step-by-step
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main